In [3]:
import numpy as np

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [5]:
m = np.zeros((3, 3), dtype = int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [8]:
m = np.random.randint(0, 10, (5, 5))
print(m)

[[9 5 6 5 5]
 [5 5 9 8 5]
 [7 6 5 9 3]
 [4 1 9 1 1]
 [0 3 1 8 9]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [11]:
m = np.random.randint(0, 2, (4, 4))
print(m)

[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 1 0 1]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [14]:
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[4 6 1 1 5]
[1 9 3 1 7]
[ 5 15  4  2 12]
[ 3 -3 -2  0 -2]
[ 4 54  3  1 35]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [16]:
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(np.dot(a, b))

148


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [19]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 3))
print(np.dot(m1, m2))

[[ 84 112  78]
 [ 12  22  33]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

m = np.random.randint(1, 11, (3, 3))
m_inv = np.linalg.inv(m)
print(m_inv)

Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [23]:
m = np.random.randint(0, 2, (4, 4))
print(m.T)

[[1 0 0 1]
 [0 1 0 0]
 [0 0 0 0]
 [1 1 0 0]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [26]:
m = np.random.randint(1, 11, (3, 4))
a = np.random.randint(1 , 11, 4)
print(m * a)

[[  8  32  50   3]
 [ 32  48 100  27]
 [ 72  32  60  24]]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [28]:
m = np.random.random((3, 3))
a = np.random.random(3)
print(m * a)

[[0.75267675 0.35932931 0.02033767]
 [0.43840962 0.24666425 0.35198898]
 [0.18185075 0.15660303 0.35143278]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [29]:
m_1 = np.random.randint(1, 11, (2, 2))
m_2 = np.random.randint(1, 11, (2, 2))
print(m_1 * m_2)

[[54 27]
 [10 14]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [4]:
m_1 = np.random.randint(1, 11, (2, 2))
m_2 = np.random.randint(1, 11, (2, 2))
print(np.dot(m_1, m_2))

[[37 91]
 [42 84]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [5]:
m = np.random.randint(1, 100, (5, 5))
print(m.sum())

1225


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [6]:
m_1 = np.random.randint(1, 11, (5, 5))
m_2 = np.random.randint(1, 11, (5, 5))
print(m_1 - m_2)

[[ 2  5  0 -7 -3]
 [ 2 -1 -8  7 -3]
 [ 3  6 -1 -4 -1]
 [-4 -7 -2  1  2]
 [ 3  9  0 -3 -5]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [9]:
m = np.random.randint(1, 11, (3, 3))
print(m)
print(np.sum(m, axis=1, keepdims=True))

[[ 1  1 10]
 [ 9 10  1]
 [ 9  2  7]]
[[12]
 [20]
 [18]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [10]:
m = np.random.randint(1, 11, size=(3, 4))
m_square = np.square(m)
print(m)
print(m_square)Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

[[ 6  2 10  9]
 [ 5  8  4  4]
 [ 7  9  6  2]]
[[ 36   4 100  81]
 [ 25  64  16  16]
 [ 49  81  36   4]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [11]:
a = np.random.randint(1, 51, size=4)
a_square = np.square(a)
print(a)
print(a_square)

[14 30 22 42]
[ 196  900  484 1764]
